const songs = [
    { name:"NEXT-NCTS", file:"NEXT-NCTS.mp3", image:"1.jpg" },
    { name:"FRAGMENT", file:"Fragment.mp3", image:"2.jpg" },
    { name:"LUZ ROZA", file:"Luz Roza.mp3", image:"3.jpg" },
    { name:"NO DESCENDO", file:"No Descendo.mp3", image:"4.jpg" },
    { name:"VAI SENTAR", file:"Vai Sentar.mp3", image:"5.jpg" },
    { name:"X-TALI", file:"X- TALI.mp3", image:"6.jpg" },
    { name:"MATADORA", file:"MATADORA.mp3", image:"7.jpg" },
    { name:"OLHA MENSAGEM", file:"Olha Mensagem.mp3", image:"8.jpg" },
    { name:"REVENGE!", file:"REVENGE!.mp3", image:"9.jpg" },
    { name:"SENTO", file:"SENTO.mp3", image:"10.jpg" },
    { name:"Sol Vibra", file:"Sol Vibra .mp3", image:"1.jpg" },
    { name:"Amor Na Praia", file:"Amor Na Praia.mp3", image:"2.jpg" },
    { name:"FUNK SIGILO SLOWED", file:"FUNK SIGILO SLOWED.mp3", image:"3.jpg" },
    { name:"FRAGMENT SLOWED", file:"Fragment slowed.mp3", image:"4.jpg" },
    { name:"LUZ ROJA SLOWED", file:"Luz Roja Slowed.mp3", image:"5.jpg" },
    { name:"TIKI TIKI", file:"TIKI TIKI.mp3", image:"6.jpg" },
    { name:"ENVY SLOWED", file:"envy slowed.mp3", image:"7.jpg" },
    { name:"MONTAGEM COMA", file:"MONTAGEM COMA.mp3", image:"3.jpg" },
    { name:"FUNK CRIMINAL", file:"FUNK CRIMINAL.mp3", image:"4.jpg" },
    { name:"FUNK UNIVERSO", file:"FUNK UNIVERSO.mp3", image:"5.jpg" },
    { name:"LOUCURA LETAL", file:"LOUCURA LETAL.mp3", image:"6.jpg" },
    { name:"Los Voltage!", file:"Los Voltage!.mp3", image:"7.jpg" },
    { name:"Matushka Ultrafunk", file:"Matushka Ultrafunk.mp3", image:"8.jpg" },
    { name:"NO BATIDO", file:"NO BATIDO.mp3", image:"9.jpg" },
    { name:"ODNOGO ULTRAFUNK", file:"ODNOGO ULTRAFUNK.mp3", image:"10.jpg" },
    { name:"VOCE NA MIRA", file:"VOCE NA MIRA - Hwungii, DJ VGK1.mp3", image:"2.jpg" }
  ];
